version: '2'

services:
    php:
        build: ./docker/php
        depends_on:
            - db
        volumes:
            - .:/var/www/mycms
            - ~/.ssh:/root/_ssh:ro
            - ./app/logs:/var/log/mycms
        expose:
            - "9000"
        environment:
            YII_ENV: dev
            MYCMS_DB_HOST: 'db'
    nginx:
        build: ./docker/nginx
        depends_on:
            - php
        volumes_from:
            - php
        volumes:
            - ./app/logs:/var/log/nginx
        ports:
            - "80:80"
    db:
        build: ./docker/db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ''
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_DATABASE: ifmo
            MYSQL_USER: root
            MYSQL_PASSWORD: ''
        volumes:
            - db_data:/var/lib/mysql
volumes:
    db_data: